### ISSUE TITLE
Unsupported argument: An argument named "region" is not expected here.

### ISSUE THREAD

**Issue by zhujian0805** [ernw/steampipe-plugin-openstack#4]
I'm testing the openstack plugin, but i got "Unsupported argument: An argument named "region" is not expected here."

```
connection "openstack_production_regionone" {
  plugin    = "ernw/openstack"
  identity_endpoint= "https://keystone.cloud.example.com/v3"
  username = "XXX"
  password = "********"
  region = "regionone"
  project_name = "projectA"
  domain_name = "production"
}
```

**Comment by gdebus** [comment]
Hi @zhujian0805,

could you sent me pls a respective excerpt of the logfile. Under Linux you should find it here: `~/.steampipe/logs`. 

Also pls send me the current version of the plugin you are using. You can do this by running following command:
`steampipe plugin list`.

Thanks!

**Comment by zhujian0805** [comment]
Thanks for reply, looks like after i upgrade to the latest version, it works now.
I have another issue, can you add the support for 'project_name' = '*', the reason is because i have around 20 regions, and 60 projects in each region, if i go the configuration path, i would need too man connections, could you add that feature?

this would also needed for all the resources, like flavor, network, volumes and so

if need another issue opened, let me know. appreciate!

**Comment by gdebus** [comment]
Hi @zhujian0805,
good to see that it also works for you! Could you please open a new issue for this further feature request? Then we can discuss it there. Thank you!
